# Generated by Django 4.2.5 on 2023-10-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('talaba', models.BooleanField()),
                ('sana', models.DateField()),
                ('rasm', models.FileField(upload_to='')),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
    ]
