# Generated by Django 4.2.5 on 2023-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkaunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('sana', models.DateField()),
                ('talaba_soni', models.PositiveIntegerField()),
                ('sayt', models.URLField()),
                ('yillik', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
