# Generated by Django 4.2.5 on 2023-10-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkaunt', '0003_alter_kontakt_ism_alter_kontakt_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='sana',
            field=models.DateField(auto_now_add=True, verbose_name="Ro'yhatdan o'tgan sanasi"),
        ),
    ]
