# Generated by Django 4.2.5 on 2023-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkaunt', '0005_kontakt_jins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('jins', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('kasb', models.CharField(max_length=30)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('oylik', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='jins',
            field=models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=6),
        ),
    ]
