# Generated by Django 4.2.5 on 2023-10-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akkaunt', '0008_alter_foydalanuvchi_talaba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nazoratchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('kasb', models.CharField(blank=True, max_length=30)),
                ('yosh', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imtihon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=100, null=True)),
                ('sana', models.DateField(blank=True, null=True)),
                ('nazoratchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkaunt.nazoratchi')),
                ('talabalar', models.ManyToManyField(to='akkaunt.talaba')),
            ],
        ),
    ]
