# Generated by Django 4.2.5 on 2023-10-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akkaunt', '0009_nazoratchi_imtihon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.PositiveIntegerField(verbose_name='Narxi ... so`m')),
                ('kelgan_sana', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nashriyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(blank=True, null=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkaunt.kitob')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkaunt.sotuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='nashriyoti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akkaunt.nashriyot'),
        ),
    ]
