# Generated by Django 4.2.5 on 2023-10-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('asosiy', models.BooleanField(blank=True, null=True)),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumot.yonalish')),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('jins', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=6)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('daraja', models.CharField(blank=True, choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Professor', 'Professor')], max_length=15)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumot.fan')),
            ],
        ),
    ]
